beadando/KepRendszerezo/KepRendszerezo/Controllers/FolderContentController.cs
using KepRendszerezo.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace KepRendszerezo.Controllers
{
    public class FolderContentController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Display(int azon)
        {
            if(HttpContext.Session.GetString("DisplayPicSize") == null)
            {
                HttpContext.Session.SetString("DisplayPicSize", "200");
            }
            ViewBag.PictSize = int.Parse(HttpContext.Session.GetString("DisplayPicSize"));

            HttpContext.Session.SetString("ModFolderId", azon.ToString());

            mydata md = new mydata();
            List<int> ids = new List<int>();
            foreach (StoredPicture stp in md.StoredPictures)
            {
                if (stp.FolderId == azon)
                {
                    ids.Add(stp.PictureId);
                }
            }

            ViewBag.Ids = ids;
            ViewBag.Images = md.Pictures;
            ViewBag.Fldrs = md.Folders;
            ViewBag.FdrID = azon;
            return View();
        }

        public IActionResult Modify(int azon)
        {
            mydata md = new mydata();
            foreach (Folder fldr in md.Folders)
            {
                if (fldr.Id == azon)
                {
                    ViewBag.FldrToMod = fldr;
                    HttpContext.Session.SetString("ModFolderId", azon.ToString());
                    break;
                }
            }
            return View();
        }
        

        [HttpPost]
        public IActionResult ModifyFolder(Folder fold)
        {
            fold.Colour = HttpContext.Request.Form["fdrCol"];
            fold.Id = int.Parse(HttpContext.Session.GetString("ModFolderId"));
            if (fold.Date.Year < 1754)
            {
                fold.Date = DateTime.Parse("9000/1/1");
            }

            mydata md = new mydata();
            foreach (Folder fldr in md.Folders)
            {
                if (fldr.Id == fold.Id)
                {
                    fldr.Name = fold.Name;
                    fldr.Date = fold.Date;
                    fldr.People = fold.People;
                    fldr.Location = fold.Location;
                    fldr.Colour = fold.Colour;
                    break;
                }
            }
            md.SaveChanges();

            return View();
        }


        public IActionResult Delete(int azon)
        {
            ProcedureHelper.DeleteFromAllTables(azon);
            return View();
        }



        public ActionResult Diag(string path)
        {
            string pathToUse = path;
            Bitmap b = new Bitmap(pathToUse);
            Graphics g = Graphics.FromImage(b);
            
            MemoryStream memoryStream = new MemoryStream();
            b.Save(memoryStream, ImageFormat.Jpeg);

            memoryStream.Seek(0, SeekOrigin.Begin);
            return File(memoryStream, "image/jpg");
        }


        [HttpPost]
        public IActionResult AddNewPicture(Picture pic)
        {
            string fName = HttpContext.Request.Form["uploadFile"];

            string[] fNames = fName.Split(',');

            FotoModel fm = new FotoModel(fName);
            string[] fullFilePaths = fm.FPath;


            mydata md = new mydata();
            for (int i = 0; i < fNames.Length; i++)
            {
                Picture PicToAdd = new Picture();
                PicToAdd.Name = fNames[i];
                PicToAdd.Path = fullFilePaths[i];
                md.Pictures.Add(PicToAdd);
            }
            md.SaveChanges();


            mydata secondMd = new mydata();
            for (int i = 0; i < fNames.Length; i++)
            {
                foreach (Picture pict in secondMd.Pictures)
                {
                    if (pict.Name == fNames[i])
                    {
                        StoredPicture strdNewPic = new StoredPicture();
                        strdNewPic.PictureId = pict.Id;
                        strdNewPic.FolderId = int.Parse(HttpContext.Session.GetString("ModFolderId"));
                        secondMd.StoredPictures.Add(strdNewPic);
                        break;
                    }
                }
            }
            secondMd.SaveChanges();

            ViewBag.FID = int.Parse(HttpContext.Session.GetString("ModFolderId"));
            return View();
        }

        [HttpPost]
        public IActionResult ChangePictureSize()
        {
            string radioVal = Request.Form["radioS"];
            HttpContext.Session.SetString("DisplayPicSize", radioVal);

            ViewBag.FID = int.Parse(HttpContext.Session.GetString("ModFolderId"));
            return View();
        }
    }
}

beadando/KepRendszerezo/KepRendszerezo/Views/FolderContent/AddNewPicture.cshtml
A kép(ek) sikeresen hozzáadva!
<br />
@Html.ActionLink("Vissza a főoldalra", "index", "home")
<br />
<br />
>@Html.ActionLink("Mappa megnyitása", "display", "foldercontent", new { azon = ViewBag.FID })

beadando/KepRendszerezo/KepRendszerezo/Views/FolderContent/ChangePictureSize.cshtml
A képek mérete megjelenéskor módosítva!
<br />
@Html.ActionLink("Vissza a főoldalra", "index", "home")
<br />
<br />
>@Html.ActionLink("Mappa megnyitása", "display", "foldercontent", new { azon = ViewBag.FID })

beadando/KepRendszerezo/KepRendszerezo/Views/FolderContent/Delete.cshtml
Sikeresen törölte a mappát!
<br />
@Html.ActionLink("Vissza a főoldalra", "index", "home")

beadando/KepRendszerezo/KepRendszerezo/Views/FolderContent/Display.cshtml
@model KepRendszerezo.Models.Picture

<div class="text-center">

    @foreach (Folder f in ViewBag.Fldrs)
    {
        if (f.Id == ViewBag.FdrID)
        {
            <label>Mappa neve: @f.Name</label><br />
            <label>Dátum: @f.Date.ToShortDateString()</label><br />
            <label>Helyszín: @f.Location</label><br />
            <label>Személyek: @f.People</label><br />
            break;
        }
    }
</div>

<br />
<br />
Képek méretének módosításához válasszon opciót:
<br />
@using (Html.BeginForm("ChangePictureSize", "FolderContent", FormMethod.Post))
{
    <label>Kicsi</label>
    <input id="Radio1" name="radioS" type="radio" value="200" checked />
    <br />
    <label>Közepes</label>
    <input id="Radio2" name="radioS" type="radio" value="350" />
    <br />
    <label>Nagy</label>
    <input id="Radio3" name="radioS" type="radio" value="500" />
    <br />
    <input type="submit" value="Méret módosítása">
    <br />

}



<div class="text-center">

    @foreach (Picture pic in ViewBag.Images)
    {
        if (ViewBag.Ids.Contains(pic.Id))
        {
            <img src="@Url.Action("Diag", new { path = pic.Path })" width="@ViewBag.PictSize" />

        }
    }
</div>
<br />
<br />
<br />
<br />

Új kép(ek) hozzáadásához válassza ki a fájlokat majd kattintson az "Új kép(ek) hozzáadása" gombra!
@using (Html.BeginForm("AddNewPicture", "FolderContent", FormMethod.Post))
{
    <input type="file" name="uploadFile" accept=".jpg, .jpeg, .png" multiple required>
    <br />
    <br />
    <input type="submit" value="Új kép(ek) hozzáadása">
    <br />

}

beadando/KepRendszerezo/KepRendszerezo/Views/FolderContent/Modify.cshtml
@model KepRendszerezo.Models.Folder

Itt módosíthatja a mappa adatait!
<br />


@using (Html.BeginForm("ModifyFolder", "FolderContent", FormMethod.Post))
{
    <label>Mappa neve: </label><label>@ViewBag.FldrToMod.Name</label><br />
    <label>Mappa új neve: </label>
    @Html.TextBoxFor(m => m.Name, new { required = "required" })<br />
    <label>Dátum: </label><label>@ViewBag.FldrToMod.Date</label><br />
    <label>Új dátum: </label>
    @Html.EditorFor(m => m.Date)
    <br />
    <label>Személyek: </label><label>@ViewBag.FldrToMod.People</label><br />
    <label>Új személyek(pl: Laci, Peti): </label>
    @Html.TextBoxFor(m => m.People, new { required = "required" })
    <br />
    <label>Helyszín: </label><label>@ViewBag.FldrToMod.Location</label><br />
    <label>Új helyszín: </label>
    @Html.TextBoxFor(m => m.Location, new { required = "required" })
    <br />
    <label>Mappa színe: </label><label>@ViewBag.FldrToMod.Colour</label><br />
    <label>Mappa új színe: </label>
    <input type="color" name="fdrCol" value="@ViewBag.FldrToMod.Colour"/>
    <br />
    <input type="submit" value="Mappa adatainak módosítása">
    <br />
}

beadando/KepRendszerezo/KepRendszerezo/Views/FolderContent/ModifyFolder.cshtml
Sikeresen módosította a mappa adatait!
<br />
@Html.ActionLink("Vissza a főoldalra", "index", "home")