beadando/KepRendszerezo/KepRendszerezo/Controllers/FolderListController.cs
using Aspose.Zip;
using KepRendszerezo.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace KepRendszerezo.Controllers
{
    public class FolderListController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Listing(Folder fldr)
        {
            fldr.Location = HttpContext.Request.Form["FilterLoc"];

            bool IsNamesEmpty = false;
            if(fldr.People == null)
            {
                fldr.People = "";
                IsNamesEmpty = true;
            }
            string[] persons = fldr.People.Split(", ");
            ViewBag.EmptyNames = IsNamesEmpty;

            ViewBag.FilterLocat = fldr.Location;
            ViewBag.FilterPers = persons;
            mydata md = new mydata();
            ViewBag.Adatb = md.Folders;
            return View();
            
        }

        [HttpPost]
        public IActionResult AddNewFolder(Folder fold)
        {
            fold.Colour = HttpContext.Request.Form["szin"];
            if(fold.Date.Year<1754)
            {
                fold.Date = DateTime.Parse("9000/1/1");
            }
            mydata md = new mydata();
            md.Folders.Add(fold);
            md.SaveChanges();
            
            return View();
        }


        [HttpPost]
        public IActionResult Ziping(Folder fold)
        {
            string Infos = HttpContext.Request.Form["ZipFold"];
            fold.Name = Infos.Split(" - ")[0];
            fold.Date = DateTime.Parse(Infos.Split(" - ")[1]);
            string archiveName = fold.Name + "__" + fold.Date.Year + "_" + fold.Date.Month + "_" + fold.Date.Day + ".zip";

            List<int> picIds = ProcedureHelper.GiveBackPictureIdsFromFolderNameAndDate(ref fold);

            ProcedureHelper.ZiperProc(archiveName, picIds);

            return View();
        }
    }
}

beadando/KepRendszerezo/KepRendszerezo/Views/FolderList/AddNewFolder.cshtml
Sikeresen hozzáadta az új mappát!
<br />
@Html.ActionLink("Vissza a főoldalra", "index", "home")

beadando/KepRendszerezo/KepRendszerezo/Views/FolderList/Listing.cshtml
@model KepRendszerezo.Models.Folder
<br />
<br />


<div class="text-center">
    <table border="1">


        @foreach (Folder fd in ViewBag.Adatb)
        {
            string[] ContentPersons = fd.People.Split(", ");
            bool acceptable = true;
            foreach (string person in ViewBag.FilterPers)
            {
                if (!ContentPersons.Contains(person))
                {
                    acceptable = false;
                    break;
                }
            }


            if (fd.Location == ViewBag.FilterLocat || ViewBag.FilterLocat == "Mind")
            {
                if (acceptable || ViewBag.EmptyNames)
                {
                    <tr height="300px" style="background-color:@fd.Colour">
                        <td width="200px">@fd.Name</td>
                        <td>@fd.Date.ToShortDateString()</td>
                        <td>@Html.ActionLink("Mappa megnyitása", "display", "foldercontent", new { azon = fd.Id })</td>
                        <td>@Html.ActionLink("Mappa adatainak módosítása", "modify", "foldercontent", new { azon = fd.Id })</td>
                        <td>@Html.ActionLink("Mappa törlése", "delete", "foldercontent", new { azon = fd.Id })</td>
                    </tr>
                }

            }
        }
    </table>

</div>

<br />
<br />
<br />


@using (Html.BeginForm("AddNewFolder", "FolderList", FormMethod.Post))
{

    <label>Új mappa hozzáadása:</label>
    <br />
    <label>Mappa neve:</label>
    @Html.TextBoxFor(m => m.Name, new { required="required"})
    <br />
    <label>Dátum:</label>
    @Html.EditorFor(m => m.Date)
    <br />
    <label>Személyek:</label>
    @Html.TextBoxFor(m => m.People, new { required = "required" })
    <br />
    <label>Helyszín:</label>
    @Html.TextBoxFor(m => m.Location, new { required = "required" })
    <br />
    <label>Mappa színe:</label>
    <input type="color" name="szin" />
    <br />
    <input type="submit" value="Új mappa létrehozása">
    <br />
    <br />
    <br />
}

Ide kattintva kiválaszthatja hogy melyik mappát szeretné letölteni:<br />

@using (Html.BeginForm("Ziping", "FolderList", FormMethod.Post))
{
    <select id="Sel" name="ZipFold" required>
        @foreach (Folder fol in ViewBag.Adatb)
        {
            <option>@fol.Name - @fol.Date</option>
        }
    </select>
    <br />
    <br />
    <input type="submit" value="Mappa letöltése">
    <br />
}

beadando/KepRendszerezo/KepRendszerezo/Views/FolderList/Ziping.cshtml
Mappa sikeresen letöltve!
<br />
@Html.ActionLink("Vissza a főoldalra", "index", "home")